Repository fga-eps-mds/2022-2-IsItKbs, pull requests merged in 2022-12, with the labels that each got.

#67 Criação da security policy
  docs/SECURITY.md
Labels: documentation, community standards

#72 Comprimindo o Modelo Escolhido
  docs/images/diagramaPacotes.png
  docs/images/userstorymap_v1.png
  src/models/logistic-regression-model.py
Labels: evaluation, training

#73 Criação do relatório de padrões da comunidade do github
  CONTRIBUTING.md
Labels: documentation, community standards

#94 Atualização README.md
  README.md
Labels: documentation, enhancement

#97 Alterando README
  README.md
Labels: documentation, organization
