Repository fga-eps-mds/2022-2-IsItKbs, pull requests merged in 2023-01, with the labels that each got.

#109 Paulo.readme
  CONTRIBUTING.md
  README.EN.md
  description.md
Labels: documentation

#106 Foi feita a criação dos testes unitários e dos arquivos yml do coveralls e de automação
  .coverage
  .coveralls.yml
  .github/workflows/python-package.yml
  isitkbs.egg-info/requires.txt
  isitkbs/__pycache__/__init__.cpython-310.pyc
  isitkbs/__pycache__/ks.cpython-310.pyc
  tests/__pycache__/test_isitkbs.cpython-310-pytest-7.2.1.pyc
  tests/test_isitkbs.py
Labels: bug, enhancement

#120 Integração da classe isitkbs no ks.py
  isitkbs/ks.py
  notebooks/ks_object.ipynb
  notebooks/test_kbs_replace.ipynb
Labels: enhancement
